version: 2

models:

  - name: stg_customer_transactions_fraud
    description: My transformation written in Python
    config:
      database: FEATURE_STORE_DBT_DEMO
      schema: FS_DBT_DEMO

  - name: stg_fraud_transactions
    description: My transformation written in Python
    config:
      database: FEATURE_STORE_DBT_DEMO
      schema: FS_DBT_DEMO
    
  - name: terminals
    description: My transformation written in Python
    config:
      database: FEATURE_STORE_DBT_DEMO
      schema: FS_DBT_DEMO
      materialized: table
      tags: ['python']

  - name: transactions
    description: My transformation written in Python
    config:
      database: FEATURE_STORE_DBT_DEMO
      schema: FS_DBT_DEMO
      materialized: table
      tags: ['python']

  - name: customers
    description: My transformation written in Python
    config:
      database: FEATURE_STORE_DBT_DEMO
      schema: FS_DBT_DEMO
      materialized: table
      tags: ['python']

